# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: rep

report_sizes: true

builds:
  - id: rep
    builder: rust
    binary: rep
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-pc-windows-gnullvm
    flags:
      - --release

checksum:
  name_template: checksums.txt
  algorithm: sha256

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

scoops:
  - repository:
      owner: gechr
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    directory: bucket
    homepage: https://github.com/gechr/rep
    description: Fast find-and-replace tool
    license: Apache-2.0
