name: release

permissions: {}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-tag:
    permissions:
      contents: read
    uses: gechr/actions/.github/workflows/verify-tag.yaml@d312df23aa0a2e809547cf08034ee3522ddd6be9 # v0.0.3

  publish:
    needs: verify-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.RELEASER_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
          repositories: homebrew-tap
          permission-contents: write

      - uses: taiki-e/install-action@e49978b799e49ff429d162b7a30601a569ab6538 # v2.81.1
        with:
          tool: cargo-zigbuild

      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.13.0
          use-cache: false

      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: gechr/homebrew-publish-formula@04c96853dce59cfbfca97503d2cc625cb3321cee # v1.0.5
        with:
          name: rep
          desc: "Fast find-and-replace tool"
          token: ${{ steps.app-token.outputs.token }}
          version: ${{ github.ref_name }}
          homepage: https://github.com/${{ github.repository }}
          head-depends-on: rust
          head-build-binary: target/release/rep
          completion-args: "--completions"
          shell-parameter-format: ""
