name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: {}

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
    uses: gechr/actions/.github/workflows/release.yaml@854917523e0f0f5208e64c557bd645509944170b # v0.2.6
    secrets:
      RELEASER_APP_PRIVATE_KEY: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
    with:
      language: rust
      name: rep
      desc: "Fast find-and-replace tool"
